// Generated by gencpp from file robot_communication/encoder_comm.msg
// DO NOT EDIT!


#ifndef ROBOT_COMMUNICATION_MESSAGE_ENCODER_COMM_H
#define ROBOT_COMMUNICATION_MESSAGE_ENCODER_COMM_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_communication
{
template <class ContainerAllocator>
struct encoder_comm_
{
  typedef encoder_comm_<ContainerAllocator> Type;

  encoder_comm_()
    : left_enc(0.0)
    , right_enc(0.0)  {
    }
  encoder_comm_(const ContainerAllocator& _alloc)
    : left_enc(0.0)
    , right_enc(0.0)  {
  (void)_alloc;
    }



   typedef float _left_enc_type;
  _left_enc_type left_enc;

   typedef float _right_enc_type;
  _right_enc_type right_enc;





  typedef boost::shared_ptr< ::robot_communication::encoder_comm_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_communication::encoder_comm_<ContainerAllocator> const> ConstPtr;

}; // struct encoder_comm_

typedef ::robot_communication::encoder_comm_<std::allocator<void> > encoder_comm;

typedef boost::shared_ptr< ::robot_communication::encoder_comm > encoder_commPtr;
typedef boost::shared_ptr< ::robot_communication::encoder_comm const> encoder_commConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_communication::encoder_comm_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_communication::encoder_comm_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_communication::encoder_comm_<ContainerAllocator1> & lhs, const ::robot_communication::encoder_comm_<ContainerAllocator2> & rhs)
{
  return lhs.left_enc == rhs.left_enc &&
    lhs.right_enc == rhs.right_enc;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_communication::encoder_comm_<ContainerAllocator1> & lhs, const ::robot_communication::encoder_comm_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_communication

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_communication::encoder_comm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_communication::encoder_comm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_communication::encoder_comm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_communication::encoder_comm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_communication::encoder_comm_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_communication::encoder_comm_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_communication::encoder_comm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "62d5c2afe8311d58c8b7b83a4571d468";
  }

  static const char* value(const ::robot_communication::encoder_comm_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x62d5c2afe8311d58ULL;
  static const uint64_t static_value2 = 0xc8b7b83a4571d468ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_communication::encoder_comm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_communication/encoder_comm";
  }

  static const char* value(const ::robot_communication::encoder_comm_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_communication::encoder_comm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# encoder_comm.msg\n"
"float32 left_enc\n"
"float32 right_enc\n"
;
  }

  static const char* value(const ::robot_communication::encoder_comm_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_communication::encoder_comm_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left_enc);
      stream.next(m.right_enc);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct encoder_comm_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_communication::encoder_comm_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_communication::encoder_comm_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "left_enc: ";
    Printer<float>::stream(s, indent + "  ", v.left_enc);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "right_enc: ";
    Printer<float>::stream(s, indent + "  ", v.right_enc);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_COMMUNICATION_MESSAGE_ENCODER_COMM_H
