// Generated by gencpp from file robot_communication/vision_pattern.msg
// DO NOT EDIT!


#ifndef ROBOT_COMMUNICATION_MESSAGE_VISION_PATTERN_H
#define ROBOT_COMMUNICATION_MESSAGE_VISION_PATTERN_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_communication
{
template <class ContainerAllocator>
struct vision_pattern_
{
  typedef vision_pattern_<ContainerAllocator> Type;

  vision_pattern_()
    : curvature(0.0)
    , offset(0.0)
    , ci_dist(0.0)  {
    }
  vision_pattern_(const ContainerAllocator& _alloc)
    : curvature(0.0)
    , offset(0.0)
    , ci_dist(0.0)  {
  (void)_alloc;
    }



   typedef float _curvature_type;
  _curvature_type curvature;

   typedef float _offset_type;
  _offset_type offset;

   typedef float _ci_dist_type;
  _ci_dist_type ci_dist;





  typedef boost::shared_ptr< ::robot_communication::vision_pattern_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_communication::vision_pattern_<ContainerAllocator> const> ConstPtr;

}; // struct vision_pattern_

typedef ::robot_communication::vision_pattern_<std::allocator<void> > vision_pattern;

typedef boost::shared_ptr< ::robot_communication::vision_pattern > vision_patternPtr;
typedef boost::shared_ptr< ::robot_communication::vision_pattern const> vision_patternConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_communication::vision_pattern_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_communication::vision_pattern_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_communication::vision_pattern_<ContainerAllocator1> & lhs, const ::robot_communication::vision_pattern_<ContainerAllocator2> & rhs)
{
  return lhs.curvature == rhs.curvature &&
    lhs.offset == rhs.offset &&
    lhs.ci_dist == rhs.ci_dist;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_communication::vision_pattern_<ContainerAllocator1> & lhs, const ::robot_communication::vision_pattern_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_communication

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_communication::vision_pattern_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_communication::vision_pattern_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_communication::vision_pattern_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_communication::vision_pattern_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_communication::vision_pattern_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_communication::vision_pattern_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_communication::vision_pattern_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a56f55df37df7ce0e374235fbf98d766";
  }

  static const char* value(const ::robot_communication::vision_pattern_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa56f55df37df7ce0ULL;
  static const uint64_t static_value2 = 0xe374235fbf98d766ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_communication::vision_pattern_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_communication/vision_pattern";
  }

  static const char* value(const ::robot_communication::vision_pattern_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_communication::vision_pattern_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# vision_pattern.msg\n"
"float32 curvature\n"
"float32 offset\n"
"float32 ci_dist\n"
;
  }

  static const char* value(const ::robot_communication::vision_pattern_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_communication::vision_pattern_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.curvature);
      stream.next(m.offset);
      stream.next(m.ci_dist);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct vision_pattern_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_communication::vision_pattern_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_communication::vision_pattern_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "curvature: ";
    Printer<float>::stream(s, indent + "  ", v.curvature);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "offset: ";
    Printer<float>::stream(s, indent + "  ", v.offset);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ci_dist: ";
    Printer<float>::stream(s, indent + "  ", v.ci_dist);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_COMMUNICATION_MESSAGE_VISION_PATTERN_H
